put http://ut-smads.herokuapp.com/spots/0/statusUpdate
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxNTEiLCJleHAiOjE1OTU3MDIyNzksImlhdCI6MTU5NDgzODI3OX0.CSTsiYh2est7G__sJp5hyECc9uZ0BIdHaChvHBCP19Y

{
  "latitude" : 0.0,
  "longitude": 0.0,
  "spotStatus": "available",
  "chargeLevel": 0,
}